export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Login } from "./Login";
export { default as NavBar } from "./NavBar";
export { default as Signup } from "./Signup";
export { default as Profile } from "./Profile";
export { default as Landing } from "./Landing";
export { default as Questions } from "./Questions";
export { default as QuestionBox } from "./QuestionBox";
