export { default as Home } from "./home/Home.page";
export { default as Profile } from "./profile/Profile.page";
export { default as About } from "./about/About.page";
export { default as Landing } from "./landing/Landing.page";
export { default as Quiz } from "./quiz/Quiz.page";
export { default as Ranking } from "./ranking/Ranking.page";
export { default as Followers } from "./followers/Followers.page";
export { default as ShortAnswers } from "./ShortAnswers/ShortAnswers.page";
export { default as Test } from "./test/Test-page";
